export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART ='DELETE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';
export const FILTER_PRODUCT_BY_SIZE = 'FILTER_PRODUCT_BY_SIZE';
export const ORDER_PRODUCT_BY_PRICE = 'ORDER_PRODUCT_BY_PRICE';
